version: 1.0.{build}-{branch}

image: Visual Studio 2017
platform:
  - Win64
  - ARM
configuration:
  - Debug
  - Release

shallow_clone: true
clone_folder: c:\projects\homework_05

init:
  - set BOOST_ROOT = C:\Libraries\boost_1_67_0

# scripts to run before build
before_build:
  - echo "Running cmake... for %APPVEYOR_BUILD_WORKER_IMAGE% %PLATFORM% %CONFIGURATION%" 
  - cmake --version

build_script:
  - cmake -H"%APPVEYOR_BUILD_FOLDER%" -Bbuild -G "Visual Studio 15 2017 %PLATFORM%" -DBUILD_TESTING=ON -DBOOST_ROOT="%BOOST_ROOT%"
  - cmake --build build

#test_script:
#  - set CTEST_OUTPUT_ON_FAILURE=ON
#  - cmake --build build --target test

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true