version: 1.0.{build}-{branch}

image: Visual Studio 2017
platform:
  - Win64
  - ARM
configuration:
  - Debug
  - Release

shallow_clone: true
clone_folder: c:\projects\otus_homework

before_build:
  - echo "Running cmake... for %APPVEYOR_BUILD_WORKER_IMAGE% %PLATFORM% %CONFIGURATION%" 
  - cmake --version

build_script:
  - cmake -H"%APPVEYOR_BUILD_FOLDER%" -Bbuild -G "Visual Studio 15 2017 %PLATFORM%"
  - cmake --build build

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true